### ISSUE TITLE
Prefix vs Exact

### ISSUE THREAD

**Issue by LelandSindt** [icicimov/kubernetes-bitwarden_rs#16]
The way that I read https://github.com/dani-garcia/vaultwarden/wiki/Enabling-WebSocket-notifications

`Route the /notifications/hub endpoint to the WebSocket server` ... `Route everything else, including /notifications/hub/negotiate, to the standard Rocket server`

The `pathType` for `/notifications/hub` should be `Exact` instead of `Prefix` 

https://github.com/icicimov/kubernetes-bitwarden_rs/blob/00dc28bcf5d9b42b07bdb95c9831a229cb7c6d16/ingress.yml#L40

This is the Configuration I am using.. 

https://github.com/wizardlyEinstein/vault/blob/main/ingress.yaml#L28

But I have only started using vaultwarden this weekend.. 

Perhaps you have some other insight?

**Comment by lvnilesh** [comment]
Yes, I agree `pathType: Exact` is the right way to configure ingress for`/notifications/hub`
